# Generated by Django 4.1.7 on 2023-03-31 11:16

import audio.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('audio', audio.models.AudioField(upload_to='audio/%Y/%m/%d/')),
            ],
        ),
    ]
