# Generated by Django 4.1.7 on 2023-03-31 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_audio_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
