# Generated by Django 4.1.7 on 2023-03-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_audio_created_at_audio_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='artist',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
