# Generated by Django 4.1.7 on 2023-04-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_audio_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ('-created_at',), 'verbose_name': 'Audio', 'verbose_name_plural': 'Audios'},
        ),
    ]
