# Generated by Django 4.1.7 on 2023-04-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_alter_audio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
