# Generated by Django 4.1.7 on 2023-05-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('InProgress', 'Inprogress'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted')], default='InProgress', max_length=25),
        ),
    ]
