# Generated by Django 4.1.7 on 2023-04-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
    ]
