# Generated by Django 4.1.7 on 2023-04-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_favorite_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
