# Generated by Django 4.1.7 on 2023-04-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_playlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
